@extends('layouts.adminedit')
@section('title','Product Management Editor | iREX Admin')
@section('alias', 'Product')

@section('content')
    <form action="{{route('product.update', $product->RSkuKey)}}" method="POST">
        @csrf
        @method('PUT')

        <div class="mb-3">
            <label class="form-label">Unique Product SKU Key (Autogenerated)</label>
            <input type="text" name="RSkuKey" class="form-control" value="{{$product->RSkuKey}}" required readonly>
        </div>

        <div class="mb-3">
            <label class="form-label">Product SKU CodeName (Autogenerated)</label>
            <input type="text" name="RSkuNo" id="RSkuNo" class="form-control" value="{{$product->RSkuNo}}" required>
        </div>

        <div class="mb-3">
            <label class="form-label">Product SKU FullName</label>
            <input type="text" name="RSkuName1" class="form-control" style="text-transform: uppercase;" oninput="this.value = this.value.toUpperCase();" value="{{$product->RSkuName1}}" required>
        </div>

        <div class="mb-3">
            <label class="form-label">Product SKU ShortName</label>
            <input type="text" name="RSkuName2" id="RSkuName2" class="form-control" style="text-transform: uppercase;" oninput="this.value = this.value.toUpperCase();" value="{{$product->RSkuName2}}" required>
        </div>

        <div class="mb-3">
            <label class="form-label">Product SKU Product Name</label>
            <input type="text" name="RSkuPrName" class="form-control" style="text-transform: uppercase;" oninput="this.value = this.value.toUpperCase();" value="{{$product->RSkuPrName}}" required>
        </div>

        <div class="mb-3">
            <label class="form-label">Product SKU Brand Name</label>
            <input type="text" name="RSkuBrnName" id="RSkuBrnName" class="form-control" style="text-transform: uppercase;" oninput="this.value = this.value.toUpperCase();" value="{{$product->RSkuBrnName}}" required>
        </div>

        <div class="mb-3">
            <label class="form-label">Product SKU Price Per Unit (RM)</label>
            <input type="text" name="RSkuPrice" id="RSkuPrice" class="form-control" style="text-transform: uppercase;" oninput="this.value = this.value.toUpperCase();" value="{{$product->RSkuPrice}}" required>
        </div>

        <div class="mb-3">
            <label class="form-label">Product SKU Type</label>
            <input type="text" name="RSkuType" class="form-control" style="text-transform: uppercase;" oninput="this.value = this.value.toUpperCase();" value="{{$product->RSkuType}}" required>
        </div>

        <div class="mb-3">
            <label class="form-label">Product SKU Unit of Measurement (UoM)</label>
            <input type="text" name="RUom" class="form-control" style="text-transform: uppercase;" oninput="this.value = this.value.toUpperCase();" value="{{$product->RUom}}" required>
        </div>

        <div class="mb-3">
            <label class="form-label">Product SKU Minimum Order Quantity (Moq)</label>
            <input type="number" min="1" name="RSkuMoq" class="form-control" value="{{$product->RSkuMoq}}" required>
        </div>

        <div class="mb-3">
            <label class="form-label">Product SKU Quantity On Hand (Qoh)</label>
            <input type="number" min="0" name="RQoh" class="form-control" value="{{$product->RQoh}}" required>
        </div>

        <button type="submit" class="btn btn-primary">Modify Product</button>
        <a href="{{ route('product.index') }}" class="btn btn-secondary">Cancel</a>

    </form>
    <script src="{{asset('dist/assets/js/preader.js')}}"></script>
@endsection
